// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

type Book struct {
	ID       int32
	Title    string
	Author   string
	Year     int32
	FileUrl  string
	S3Key    string
	FileName string
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
}
