// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID     int32
	Title  string
	Author string
	Year   int32
}

type File struct {
	ID           pgtype.UUID
	OriginalName string
	S3Key        string
	MimeType     string
	Size         int64
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
}
