// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storage

import (
	"context"
)

const completeBook = `-- name: CompleteBook :exec
UPDATE books
SET file_url = $2, s3_key = $3, file_name = $4, status = 'completed'
WHERE id = $1
`

type CompleteBookParams struct {
	ID       int32
	FileUrl  string
	S3Key    string
	FileName string
}

func (q *Queries) CompleteBook(ctx context.Context, arg CompleteBookParams) error {
	_, err := q.db.Exec(ctx, completeBook,
		arg.ID,
		arg.FileUrl,
		arg.S3Key,
		arg.FileName,
	)
	return err
}

const createPendingBook = `-- name: CreatePendingBook :one
INSERT INTO books (title, author, year, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, title, author, year, file_url, s3_key, file_name, status
`

type CreatePendingBookParams struct {
	Title  string
	Author string
	Year   int32
}

func (q *Queries) CreatePendingBook(ctx context.Context, arg CreatePendingBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createPendingBook, arg.Title, arg.Author, arg.Year)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.FileUrl,
		&i.S3Key,
		&i.FileName,
		&i.Status,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const failBook = `-- name: FailBook :exec
UPDATE books SET status = 'failed' WHERE id = $1
`

func (q *Queries) FailBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, failBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, year, file_url, s3_key, file_name, status
FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.FileUrl,
		&i.S3Key,
		&i.FileName,
		&i.Status,
	)
	return i, err
}

const getPendingBooks = `-- name: GetPendingBooks :many
SELECT id, title, author, year, file_url, s3_key, file_name, status
FROM books
WHERE status = 'pending' OR status = 'processing'
`

func (q *Queries) GetPendingBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getPendingBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.FileUrl,
			&i.S3Key,
			&i.FileName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, year, file_url, s3_key, file_name, status
FROM books
WHERE status = 'completed'
ORDER BY id
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.FileUrl,
			&i.S3Key,
			&i.FileName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2, author = $3, year = $4
WHERE id = $1
RETURNING id, title, author, year, file_url, s3_key, file_name, status
`

type UpdateBookParams struct {
	ID     int32
	Title  string
	Author string
	Year   int32
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Year,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.FileUrl,
		&i.S3Key,
		&i.FileName,
		&i.Status,
	)
	return i, err
}
